data_processor:
  import_path: rakam_systems.components.data_processing.data_processor.DataProcessor
  dependencies:
    - system_manager
  libraries:
    - pandas==2.1.4
    - tqdm==4.66.4

vector_store:
  import_path: rakam_systems.components.vector_search.vector_store.VectorStore
  dependencies:
    - system_manager
  libraries:
    - faiss-cpu==1.8.0.post1
    - sentence-transformers==2.6.1

vs_manager:
  import_path: rakam_systems.components.vector_search.vs_manager.VSManager
  dependencies:
    - system_manager
    - vector_store
  libraries:
    - faiss-cpu==1.8.0.post1
    - sentence-transformers==2.6.1

rag_generator:
  import_path: rakam_systems.components.rag.rag_generator.RAGGenerator
  dependencies:
    - system_manager
  libraries:
    - openai==1.37.0
    - mistralai==1.1.0

s3_file_manager:
  import_path: rakam_systems.components.connectors.file_storage.S3FileManager
  dependencies:
    - system_manager
  libraries:
    - boto3==1.34.115

llm_connector:
  import_path: rakam_systems.components.connectors.LLMconnector.LLMConnector
  dependencies:
    - system_manager
  libraries:
    - mistralai==1.1.0
    - openai==1.37.0
