---
name: "🐞 Bug Report"
description: "Report a reproducible bug or regression."
title: "[Bug] <concise summary>"
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        ## 🐞 Bug Report
        Thank you for helping us improve the project! Please fill out the following information to help us reproduce and fix the issue.

  - type: input
    id: environment
    attributes:
      label: Environment
      description: "Describe your environment (OS, Python version, package manager, etc.)"
      placeholder: "e.g. Ubuntu 22.04, Python 3.10, pip, ..."
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: "A clear and concise description of what the bug is."
      placeholder: "What happened? What did you expect to happen?"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: "How can we reproduce the bug? Please provide a minimal, complete, and verifiable example."
      placeholder: |
        1. Go to '...'
        2. Run '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs/Tracebacks
      description: "Paste any error messages, logs, or stack traces. Use code blocks for formatting."
      render: shell
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: "If applicable, add screenshots to help explain your problem."
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched the [issues](https://github.com/Rakam-AI/rakam-systems-inhouse/issues) and this bug has not been reported before.
          required: true
        - label: I have provided all necessary information above.
          required: true
