---
name: "💡 Feature Request / Improvement"
description: "Suggest a new feature, enhancement, or improvement."
title: "[Feature] <concise summary>"
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        ## 💡 Feature Request / Improvement
        Thank you for helping us improve the project! Please provide as much detail as possible.

  - type: input
    id: motivation
    attributes:
      label: Motivation
      description: "What problem are you trying to solve? Why is this feature important?"
      placeholder: "Describe the motivation or use case."
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: "Describe the solution you'd like. Include code snippets, API changes, or UI mockups if relevant."
      placeholder: "How should this feature work?"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: "Have you considered alternative solutions or workarounds?"
      placeholder: "List any alternatives you've considered."
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched the [issues](https://github.com/Rakam-AI/rakam-systems-inhouse/issues) and this feature has not been requested before.
          required: true
        - label: I have provided all necessary information above.
          required: true
